Repository listendev/action, pull requests merged in 2023-07, with the labels that each got.

#32 docs: added screenshot and demo video
  README.md
Labels: documentation, enhancement, small, bump:patch

#36 chore: clarify we don't have v1 yet
  README.md
Labels: documentation, small, bump:patch

#38 docs: revise marketplace listing
  action.yml
Labels: documentation, needs-review, small, bump:patch
